-- Création de la base de données
CREATE DATABASE IF NOT EXISTS gestion_emploi_temps;
USE gestion_emploi_temps;

-- Table Filières
CREATE TABLE filieres (
    ID_FILIERE INT(11) PRIMARY KEY AUTO_INCREMENT,
    NOM_FILIERE VARCHAR(15) NOT NULL,
    DESCRITION TEXT
);

-- Table Classes
CREATE TABLE classes (
    ID_CLASSE INT(11) PRIMARY KEY AUTO_INCREMENT,
    ID_FILIERE INT(11),
    NIVEAU INT(11),
    FOREIGN KEY (ID_FILIERE) REFERENCES filieres(ID_FILIERE)
);

-- Table Étudiants
CREATE TABLE etudiants (
    NUM_INSCRIPTION VARCHAR(15) PRIMARY KEY,
    NOM_ET VARCHAR(25) NOT NULL,
    PRENOM_ET VARCHAR(25) NOT NULL,
    ADRESSE VARCHAR(70),
    ID_CLASSE INT(11),
    FOREIGN KEY (ID_CLASSE) REFERENCES classes(ID_CLASSE)
);

-- Table Salles
CREATE TABLE salles (
    ID_SALLE INT(11) PRIMARY KEY AUTO_INCREMENT,
    NOM_SALLE VARCHAR(25) NOT NULL,
    DESCIPTION TEXT
);

-- Table Modules
CREATE TABLE modules (
    ID_MODULE VARCHAR(15) PRIMARY KEY,
    NOM_MODULE VARCHAR(25) NOT NULL,
    DESCRIPTION TEXT
);

-- Table Professeurs
CREATE TABLE professeurs (
    ID_PROF INT(11) PRIMARY KEY AUTO_INCREMENT,
    NOM_PROF VARCHAR(25) NOT NULL,
    TEL VARCHAR(12)
);

-- Table Cours
CREATE TABLE cours (
    ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    ID_CLASSE INT(11),
    ID_PROF INT(11),
    ID_SALLE INT(11),
    ID_MODULE VARCHAR(15),
    JOUR VARCHAR(12),
    HEURE_DEBUT TIME,
    HEURE_FIN TIME,
    FOREIGN KEY (ID_CLASSE) REFERENCES classes(ID_CLASSE),
    FOREIGN KEY (ID_PROF) REFERENCES professeurs(ID_PROF),
    FOREIGN KEY (ID_SALLE) REFERENCES salles(ID_SALLE),
    FOREIGN KEY (ID_MODULE) REFERENCES modules(ID_MODULE)
); 